# Generated by Django 4.0.5 on 2022-06-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_dictionary', '0002_alter_kanji_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='klc_index',
            field=models.IntegerField(help_text="Index of the kanji in Kodansha's Kanji Learner's Course book.", null=True),
        ),
    ]
