# Generated by Django 4.0.5 on 2022-06-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_dictionary', '0003_alter_kanji_klc_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='jlpt',
            field=models.IntegerField(default=0, help_text='Level where this kanji appears on the Japanese Language Proficiency Test.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanji',
            name='id',
            field=models.IntegerField(help_text='ID for the kanji.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radical',
            name='id',
            field=models.IntegerField(help_text='ID for the radical.', primary_key=True, serialize=False),
        ),
    ]
